export const products = [
  {
    id: 1,
    category: "Programming Apparel",
    name: "Python Programming Hoodie",
    price: 70.0,
    image: "/placeholder.svg?height=400&width=400",
    description: "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
    features: [
      "100% Cotton blend material",
      "Machine washable",
      "Available in multiple sizes",
      "Durable print quality",
      "Comfortable fit for coding sessions",
    ],
    type: "Clothing",
    inStock: true,
  },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
  {
    id: 1,
    category: "Programming Apparel",
    name: "Python Programming Hoodie",
    price: 70.0,
    image: "/placeholder.svg?height=400&width=400",
    description: "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
    features: [
      "100% Cotton blend material",
      "Machine washable",
      "Available in multiple sizes",
      "Durable print quality",
      "Comfortable fit for coding sessions",
    ],
    type: "Clothing",
    inStock: true,
  },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
  {
    id: 1,
    category: "Programming Apparel",
    name: "Python Programming Hoodie",
    price: 70.0,
    image: "/placeholder.svg?height=400&width=400",
    description: "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
    features: [
      "100% Cotton blend material",
      "Machine washable",
      "Available in multiple sizes",
      "Durable print quality",
      "Comfortable fit for coding sessions",
    ],
    type: "Clothing",
    inStock: true,
  },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
  {
      id: 1,
      category: "Programming Apparel",
      name: "Python Programming Hoodie",
      price: 70.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium quality hoodie featuring Python programming language design. Perfect for developers who love clean, readable code.",
      features: [
        "100% Cotton blend material",
        "Machine washable",
        "Available in multiple sizes",
        "Durable print quality",
        "Comfortable fit for coding sessions",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 2,
      category: "Programming Apparel",
      name: "Java Programming T-Shirt",
      price: 50.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Stylish t-shirt showcasing Java programming language. Ideal for Java enthusiasts and enterprise developers.",
      features: [
        "Soft cotton fabric",
        "Breathable material",
        "Modern fit design",
        "Fade-resistant print",
        "Perfect for casual wear",
      ],
      type: "Clothing",
      inStock: true,
    },
    {
      id: 3,
      category: "Programming Accessories",
      name: "JavaScript Programming Mug",
      price: 20.0,
      image: "/placeholder.svg?height=400&width=400",
      description:
        "High-quality ceramic mug with JavaScript theme. Start your coding day with your favorite beverage in style.",
      features: [
        "11oz ceramic mug",
        "Dishwasher safe",
        "Microwave safe",
        "Vibrant color print",
        "Comfortable handle grip",
      ],
      type: "Accessories",
      inStock: true,
    },
    {
      id: 4,
      category: "Programming Books",
      name: "React Development Guide",
      price: 45.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Comprehensive guide to React development with modern best practices and advanced patterns.",
      features: ["500+ pages", "Code examples", "Expert insights", "Latest React features", "Beginner to advanced"],
      type: "Books",
      inStock: true,
    },
    {
      id: 5,
      category: "Programming Accessories",
      name: "Mechanical Keyboard",
      price: 120.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Premium mechanical keyboard designed for programmers with RGB backlighting and custom switches.",
      features: ["Cherry MX switches", "RGB backlighting", "Programmable keys", "USB-C connection", "Ergonomic design"],
      type: "Hardware",
      inStock: true,
    },
    {
      id: 6,
      category: "Programming Apparel",
      name: "CSS Wizard T-Shirt",
      price: 35.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Show off your CSS skills with this magical wizard-themed programming t-shirt.",
      features: ["100% cotton", "Comfortable fit", "Unique design", "Machine washable", "Available in all sizes"],
      type: "Clothing",
      inStock: false,
    },
    {
      id: 7,
      category: "Programming Books",
      name: "Algorithm Mastery",
      price: 60.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Master data structures and algorithms with this comprehensive programming guide.",
      features: ["600+ pages", "Visual examples", "Practice problems", "Interview prep", "Multiple languages"],
      type: "Books",
      inStock: true,
    },
    {
      id: 8,
      category: "Programming Accessories",
      name: "Code Monkey Stickers Pack",
      price: 15.0,
      image: "/placeholder.svg?height=400&width=400",
      description: "Fun sticker pack featuring programming jokes and popular coding memes.",
      features: ["20 unique stickers", "Waterproof material", "Laptop friendly", "Funny designs", "High quality print"],
      type: "Accessories",
      inStock: true,
    },
];